- .travis.yml
- bors.toml
With these changes, PVS will run on some pull requests too
> Smarter detect pull requests

- Cargo.lock
- db/Cargo.toml
- deploy/Cargo.toml
- deploy/src/lib.rs
- devtool/Cargo.toml
- invoker/Cargo.toml
- invoker/src/invoke_context.rs
- invoker/src/judge.rs
- invoker/src/main.rs
- minion-cli/Cargo.toml
- minion-cli/src/main.rs
- minion-ffi/src/lib.rs
- minion/Cargo.toml
- minion/src/command.rs
- minion/src/lib.rs
- minion/src/linux/mod.rs
- soft/Cargo.toml
- Change minion Stdin/Stdout specification to hide its repr
- Do not use diesel directly in invoker
- minion-cli: better parse arguments
- Remove unused deps
bors r+
>  Several improvements

- .travis.yml
It seems that until https://github.com/holmgr/cargo-sweep/issues/11 is resolved, cargo-sweep in CI is broken
bors r+
> Don't use cargo sweep in CI

- .travis.yml
> Optimize mdbook dependencies

- all/tests/judge.rs
- all/tests/util/mod.rs
- cfg/src/lib.rs
- db/migrations/2019-02-13-163254_initial/up.sql
- db/src/repo.rs
- db/src/repo/diesel_pg.rs
- db/src/repo/memory.rs
- db/src/schema.rs
- db/src/schema_raw.rs
- devtool/src/main.rs
- devtool/src/tests.rs
- example-config/contest.toml
- example-config/userlist.txt
- frontend-engine/src/config.rs
- frontend-engine/src/gql_server/auth.rs
- frontend-engine/src/gql_server/context.rs
- frontend-engine/src/gql_server/runs.rs
- frontend-engine/src/lib.rs
- frontend-engine/src/root_auth.rs
- frontend-engine/src/security.rs
- frontend-engine/src/security/access_ck.rs
- frontend-engine/src/security/token.rs
- frontend-engine/src/security/token_mgr.rs
- frontend-engine/src/test_util.rs
- frontend-engine/tests/common/mod.rs
- frontend-engine/tests/gql.rs
Now run known its submitter
Also, Token/TokenMgr distinction was refactored
@sleirsgoevy waiting for your feedback.
> Improve access control

- configure
- deploy/bin/configure.rs
> Check that required or or optional binary dependencies are installed

- .gitignore
- src/deploy/src/lib.rs
> Fix build order

- .github/workflows/pr.yaml
- .travis.yml
- bors.toml
- scripts/ci-env.sh
- src/deploy/deps.sh
- src/devtool/src/main.rs
- src/devtool/src/tests.rs
> Github actions

- Cargo.lock
- src/db/src/lib.rs
- src/invoker/Cargo.toml
- src/invoker/src/compiler.rs
- src/invoker/src/invoke_context.rs
- src/invoker/src/invoker.rs
- src/invoker/src/judge.rs
- src/invoker/src/judge/checker_proto.rs
- src/invoker/src/judge_log.rs
- src/invoker/src/main.rs
- src/invoker/src/valuer.rs
also improves error messages
manual Box<dyn Error> -> anyhow
snafu -> thiserror
bors r+
> Improve error handling in invoker

- src/devtool/src/build.rs
> Disable 'deb' in jjs-build

- Cargo.lock
- docker-compose.yml
- docker/env.Dockerfile
- docker/invoker.Dockerfile
- docker/tools.Dockerfile
- src/deploy/src/docker.rs
- src/deploy/src/lib.rs
- src/devtool/src/build.rs
- src/frontend-engine/tests/common/mod.rs
- src/invoker/src/valuer.rs
- src/setup/Cargo.toml
- src/setup/src/lib.rs
- src/setup/src/main.rs
- src/soft/src/main.rs
- src/util/src/wait.rs
- toolchains/ld-linux/scripts/simple.sh
> Add support for `soft` to `setup`

- .github/workflows/pr.yaml
- bors.toml
- src/devtool/src/check.rs
> Split single check job into multiple

- .github/workflows/deploy.yaml
> Fix image name

- Cargo.lock
- src/deploy/Cargo.toml
- src/frontend-engine/Cargo.toml
- src/frontend/Cargo.toml
- src/invoker/Cargo.toml
> Remove unused deps

- Cargo.lock
- src/db/migrations/2019-02-13-163254_initial/down.sql
- src/db/migrations/2019-02-13-163254_initial/up.sql
- src/db/src/repo.rs
- src/db/src/repo/diesel_pg.rs
- src/db/src/repo/memory.rs
- src/db/src/schema.rs
- src/db/src/schema_raw.rs
- src/frontend-engine/src/gql_server/runs.rs
- src/invoker/src/main.rs
> Rename invocation request to invocation

- src/db/migrations/2019-02-13-163254_initial/up.sql
> Fix outdated comment

- src/minion-ffi/build.rs
- toolchains/g++/detect.sh
> Fix problem in script

- src/invoker/src/invoke_util.rs
- src/minion-cli/src/main.rs
- src/minion-ffi/src/lib.rs
- src/minion-ffi/tests/runner.c
- src/minion/src/lib.rs
- src/minion/src/linux/dominion.rs
- src/minion/src/linux/jail_common.rs
- src/minion/src/linux/zygote/setup.rs
> Add support for configuring real time limit

- src/invoker/src/compiler.rs
- src/invoker/src/judge.rs
- src/minion-ffi/src/lib.rs
- src/minion/src/lib.rs
- src/minion/src/linux.rs
> Remove ChildProcess::drop API because it is broken

- src/util/src/wait.rs
> Print address if resolution failed

- src/minion-cli/src/main.rs
> Fix `dump_argv` arg spec

- Cargo.lock
- src/e2e/Cargo.toml
- src/e2e/tests/util/mod.rs
- src/frontend-api/Cargo.toml
- src/frontend-api/src/lib.rs
- src/invoker/Cargo.toml
- src/invoker/src/invoker.rs
- src/userlist/Cargo.toml
> Bump reqwest

- deb/build.sh
- deb/jjs-oneclick
- deb/scripts/postinst
- src/deploy/bin/configure.rs
- src/deploy/src/lib.rs
Makes deb support less broken
bors r+
> Deb ci fix

- src/devtool/src/build.rs
> Fix bug in devtool-build component selection

- Cargo.lock
- src/invoker-api/src/lib.rs
- src/invoker-api/src/valuer_proto.rs
- src/invoker/src/inter_api.rs
- src/invoker/src/invoker.rs
- src/invoker/src/judge_log.rs
- src/invoker/src/main.rs
- src/svaluer/Cargo.toml
- src/svaluer/src/cfg.rs
- src/svaluer/src/fiber.rs
- src/svaluer/src/fiber/group.rs
- src/svaluer/src/lib.rs
- src/svaluer/src/main.rs
- src/svaluer/src/tests.rs
This pull request changes invoker <-> valuer protocol, and updates invoker and svaluer.
It also improves `svaluer`architecture, making it more scalable and flexible.
> Multiple judgelogs

- src/devtool/src/build.rs
- src/devtool/src/ci.rs
> No default man

- example-problems/a-plus-b/solutions/main.cpp
- src/e2e/tests/judge.rs
> Fix main solution for a-plus-b problem

- Cargo.lock
- src/svaluer/Cargo.toml
- src/svaluer/src/tests.rs
> Remove dependency

- src/devtool/src/build.rs
> Build optimized docker images

- .github/workflows/pr.yaml
> Cache udeps

- src/minion/src/lib.rs
- src/minion/src/linux/check.rs
> Small fixups

- man/src/authentication.md
- src/frontend-engine/src/root_auth.rs
> Update root login service

- .github/workflows/pr.yaml
- src/db/src/repo/diesel_pg.rs
- src/e2e/tests/judge.rs
- src/invoker/src/controller.rs
- src/invoker/src/controller/tasks.rs
- src/invoker/src/drivers.rs
- src/invoker/src/lib.rs
- src/invoker/src/main.rs
- src/invoker/src/sources.rs
- src/invoker/src/sources/background_source.rs
- src/invoker/src/sources/cli_source.rs
- src/invoker/src/sources/db_source.rs
- src/invoker/tests/separated_feedback.rs
> Rename ControllerDriver to TaskSource

- src/invoker/src/controller/notify.rs
> Fix LSU throttle duration

- .github/workflows/pr.yaml
- src/deploy/src/build_ctx.rs
> Locked build

- toolchains/g++/detect.sh
- toolchains/gcc/detect.sh
- toolchains/go/detect.sh
> Allow skipping toolchains via env vars

- src/invoker-api/src/judge_log.rs
- src/invoker-api/src/valuer_proto.rs
- src/invoker/src/worker.rs
> Fix incorrect handling of compile error

- Cargo.lock
- src/invoker/src/worker/transform_judge_log.rs
- src/invoker/src/worker/valuer.rs
- src/svaluer/Cargo.toml
- src/svaluer/src/fiber.rs
- src/svaluer/src/fiber/group.rs
> Rewrite Group representation

- toolchains/gcc/invoke-conf.yaml
> Fix gcc toolchain

- src/frontend-engine/src/api/queries.rs
> Add API to check if JJS is in dev mode

- src/deploy/bin/configure.rs
> Disable verbose output from podman

- src/frontend-engine/src/api/runs.rs
- src/frontend-engine/src/config.rs
> Frontend fix runs

- example-config/frontend.yaml
- src/frontend-engine/src/api/runs.rs
- src/frontend-engine/src/config.rs
- src/frontend-engine/src/lib.rs
- src/frontend-engine/tests/common/mod.rs
> Frontend config

- .github/workflows/pr.yaml
This will stop endless increasing cache size
bors r+
> Remove partial keys in CI cache

- .github/workflows/pr.yaml
> Do not install lxtrace in vm-sysroot CI job

- src/setup/src/main.rs
- src/setup/src/profile.rs
> Allow skipping configs copying

- src/apiserver-engine/docs/openapi-gen.json
- src/apiserver-engine/docs/openapi.yaml
- src/apiserver-engine/src/api/runs.rs
- src/gen-api-client/docs/DefaultApi.md
- src/gen-api-client/src/apis/default_api.rs
- src/invoker-api/src/judge_log.rs
- src/invoker-api/src/valuer_proto.rs
- src/invoker/src/worker.rs
- src/invoker/src/worker/exec_test.rs
- src/invoker/src/worker/transform_judge_log.rs
- src/minion/src/lib.rs
- src/minion/src/linux/dominion.rs
- src/minion/src/linux/zygote/cgroup.rs
- src/svaluer/src/fiber.rs
- src/svaluer/src/tests.rs
> Expose resource usage in protocol

- .github/workflows/pr.yaml
> Do not restore cache from partial match

- Cargo.lock
- src/apiserver-engine/Cargo.toml
- src/apiserver-engine/src/api/runs.rs
- src/apiserver-engine/src/root_auth.rs
- src/apiserver/Cargo.toml
- src/apiserver/src/main.rs
> Use plain log

- Cargo.lock
- basic-setup-profile.yaml
- example-config/invoker.yaml
- src/invoker/Cargo.toml
- src/invoker/src/config.rs
- src/invoker/src/controller.rs
- src/invoker/src/worker.rs
- src/invoker/src/worker/compiler.rs
- src/invoker/src/worker/exec_test.rs
- src/invoker/src/worker/invoke_util.rs
> Support judging without JJS_DATA/opt

- .github/workflows/pr.yaml
> Add misspell action

- src/deploy/bin/configure.rs
- src/deploy/src/cfg.rs
- src/deploy/src/lib.rs
- src/devtool/src/build.rs
> Build rustdocs

- Cargo.lock
- src/db/Cargo.toml
- src/db/src/schema/invocation.rs
Should unblock possible rewriting of apiserver
> Use json for InvokeTask

- src/ppc/src/compile.rs
- src/ppc/src/compile/builder.rs
Addresses review comments on #385
> ppc: Add some comments

- src/dist-builder/src/main.rs
Invoker will be included into distribuition soon, I hope.
> Do not build invoker

- bors.toml
- ci-data/values.yaml
> Require smoke in bors
